package commandline

const (
	LINE                       = "------------------------"
	PRESS_ENTER_TO_CONTINUE    = "Press enter to go back to menu...."
	WELCOME_MESSAGE            = "Welcome to the Youtube-scrapper App!"
	SEARCH_QUESTION            = "Please, insert a term to search on youtube:"
	TIME_SPENDER_QUESTION      = "Now, inform how many minutes you'll spend watching videos on %s?\n"
	UNSUPPORTED_OS             = "Your platform is unsupported! I can't clear terminal screen :("
	END_PROGRAM_MESSAGE        = "Thanks for using this application...."
	LINE_WITH_BRACKETS         = "|-----------------------|"
	TERM_CANNOT_BE_EMPTY       = "| Term cannot be empty  |"
	INVALID_OPTION_SELECTED    = "| [%d] invalid option!  |"
	STILL_PROCESSING_LOADER    = "| Still processing data.|\n"
	PROCESS_TAKING_TOO_LONG    = "|This is taking too long|"
	PROCESS_TRY_AGAIN_LATER    = "|Please try again latter|"
	PROCESS_WAIT_DEFAULT       = "|   Please wait.......  |"
	CHOOSE_OPTION_QUESTION     = "|Choose an option:      |"
	OPTION_1_TOP_FIVE          = "|   1 - Top 5 words     |"
	OPTION_2_TIME_SPENDED      = "|   2 - Time spended    |"
	OPTION_9_EXIT              = "|   9 - Exit            |"
	TOP_5_RESPONSE_WORDS       = "| Top 5 words founded:  |\n"
	TOP_5_RESPONSE_TITLE       = "|  Top words in Title:  |\n"
	TOP_5_RESPONSE_DESCRIPTION = "|Top words Description: |\n"
	TOTAL_TIME_SPENDED_HEADER  = "|  Total time spended:  |\n"
	TOTAL_DAYS_SPENDED_DEADER  = "|  Total days spended:  |\n"
	DAY_OF_THE_WEEK_NUMBERED   = "|------%s(%d)------|\n"
)
